### PR TITLE
Fixed conversion between Celsius and Kelvin.

### LINKED ISSUE #44: Don't do C/K conversion on read/write for Increment
The `Field::read()` and `Field::write()` are converting to/from Kelvin so that the value inside jedi is in Celsius, however this means the saved/read Increment files are wrong (as exposed by PR https://github.com/UMD-AOSC/UMD-SST/pull/43). This isn't a huge problem now, but will make interpreting dirac output awkward in the future.

The easiest solution is probably to add a `kelvin: true` line to the appropriate state I/O sections of the  yaml files and check inside `Field::read()` and `Field::write()` if that parameter exists, and only do the conversion if that parameter exists and is true.

### PR DESCRIPTION
**Pull request by loganchen39**
@travissluka Passed all tests. Implemented as you suggested at #44. Be aware when using Field::read() and Field::write(), if the netCDF file temperature var is with Kelvin unit, we need to add "Kelvin: true" in the related yaml file. 

close #44.

### CODE REVIEW

File: src/umdsst/Fields/Fields.cc [hunk 1]
```diff
@@ -195,12 +196,17 @@ namespace umdsst {
...
-          if (abs(sstData[j][i]-(missing_nc)) < epsilon)
+          if (abs(sstData[j][i]-(missing_nc)) < epsilon) {
             sstData[j][i] = missing_;
-          else
+          } else {
             // Kelvin to Celsius which JEDI use internally, will check if the
             // units is Kelvin or Celsius in the future
-            sstData[j][i] -= 273.15;
+            bool isKelvin = false;
+            if (conf.get("kelvin", isKelvin) && isKelvin)
```
Comment (travissluka) [inline src/umdsst/Fields/Fields.cc]: only comment would be to move `conf.get()` outside of the nested for loops and instead put 
```
bool isKelvin = conf.getBool("kelvin", false);
```

 at the top of the function. (which i think is our preferred syntax of getting an optional parameter with a default value defined). It's fine for now, but if we go to a much higher resolution in the future, repeatedly reparsing the yaml file here at each gridpoint might be slow.

**Review by travissluka — APPROVED** [review]

File: src/umdsst/Fields/Fields.cc (hunk 1 above)
Comment (loganchen39) [reply src/umdsst/Fields/Fields.cc]: Done, good suggestion! Passed all tests.
